"""initial schema

Revision ID: f112524fa5fd
Revises: 
Create Date: 2026-05-23 07:59:39.150214

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f112524fa5fd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('upload', 'url', name='source_type'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'downloading', 'transcribing', 'detecting', 'ready_for_review', 'exporting', 'completed', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('progress_message', sa.Text(), nullable=False),
    sa.Column('detection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('user_start_seconds', sa.Float(), nullable=True),
    sa.Column('user_end_seconds', sa.Float(), nullable=True),
    sa.Column('detection_strategy', sa.Enum('audio_spike', 'llm_transcript', 'twitch_chat', 'manual', name='detection_strategy'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('transcript_excerpt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'selected', 'rejected', 'exporting', 'exported', 'failed', name='clip_status'), nullable=False),
    sa.Column('exported_paths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clip_candidates_job_start', 'clip_candidates', ['job_id', 'start_seconds'], unique=False)
    op.create_index('ix_clip_candidates_job_status', 'clip_candidates', ['job_id', 'status'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcripts')
    op.drop_index('ix_clip_candidates_job_status', table_name='clip_candidates')
    op.drop_index('ix_clip_candidates_job_start', table_name='clip_candidates')
    op.drop_table('clip_candidates')
    op.drop_table('jobs')
    # ### end Alembic commands ###
    # Drop native enum types (autogenerate tidak menanganinya — jika tidak,
    # upgrade ulang setelah downgrade gagal dengan "type already exists").
    bind = op.get_bind()
    sa.Enum(name='clip_status').drop(bind, checkfirst=False)
    sa.Enum(name='detection_strategy').drop(bind, checkfirst=False)
    sa.Enum(name='job_status').drop(bind, checkfirst=False)
    sa.Enum(name='source_type').drop(bind, checkfirst=False)
